version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src" # Location of package manifests
    schedule:
      interval: "daily"
      time: "01:00" #UTC
    labels:
      - ".net"
      - "dependencies"
    target-branch: "dependabot"
    open-pull-requests-limit: 5