version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "core" # Location of package manifests
    schedule:
      interval: "daily"
      time: "01:00" #UTC
    labels:
      - ".net"
      - "dependencies"
    target-branch: "main"
    open-pull-requests-limit: 7
    ignore:
    - dependency-name: "*"
      update-types:
      - "version-update:semver-major"
