name: Update dependabot configuration file

env:
  nextr: "${{ secrets.NEXT_RELEASE }}"

on:
  pull_request_target:
    types: [closed]
    branches: 
      - "rc/now"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Run dependabot config generator"
          run: echo "1"
        
        - name: "Run dependabot config generator 1"
          if: "${{ env.nextr == 'github.event.pull_request.base.ref' }}"
          run: echo 2
