name: Update dependabot configuration file

env:
  branch: "${{ secrets.NEXT_RELEASE }}"

on:
  pull_request_target:
    types: [closed]
    branches: 
      - "rc/now"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Run dependabot config generator"
          run: echo ${{ env.branch }}
        
        - name: "Run dependabot config generator 1"
          if: github.event.pull_request.merged == true
          run: echo ${{ env.branch }}
