name: Update dependabot configuration file

env:
  nextr: "${{ secrets.NEXT_RELEASE }}"
  prb: "${{ github.event.pull_request.base.ref }}"

on:
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Run dependabot config generator 1"
          run: echo "1"
        
        - name: "Run dependabot config generator 2"
          if: "${{ env.nextr == 'xxx' && github.event.pull_request.merged == true }}"
          run: echo "2"
          
        - name: "Run dependabot config generator 3"
          run: echo "3"
