name: Update dependabot configuration file

env:
  nextr: "${{ secrets.NEXT_RELEASE }}"
  prb: "${{ github.event.pull_request.base.ref }}"

on:
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Run dependabot config generator"
          run: echo "1"
        
        - name: "Run dependabot config generator 1"
          if: "${{ env.nextr == env.prb }}"
          run: echo "2"
